### ISSUE TITLE
Can not authenticate migrated accounts

### ISSUE THREAD

**Issue by KristN1** [Lucino772/pymojang#1]
Migrated accounts can no longer authenticate

request:
```py
mojang.account.auth.yggdrasil.authenticate(email, password)
```

response:
```
('ResourceException', 'Gone (410) - The requested resource is no longer available at the server and no forwarding address is known')
```

**Comment by Lucino772** [comment]
Can you please show the full output you have ? My account is not migrated either and I have no problem when I authenticate.

**Comment by KristN1** [comment]
I said that this happens to only accounts that have been **already migrated**

Now you probably have to use the Mictosoft's API instead I assume

**Comment by Lucino772** [comment]
Oh Sorry, but yeah you're right. I will implement the Microsoft Authentication Scheme

**Comment by Lucino772** [comment]
Version 1.3.0 now supports Microsoft accounts
