### ISSUE TITLE
mojang.connect doesn't work

### ISSUE THREAD

**Issue by BossCode45** [Lucino772/pymojang#2]
I am trying to make a sniper bot using this api but for some reason `mojang.connect("EMAIL", "PASSWORD")` is not working. It is reporting the error `TypeError: <lambda>() got an unexpected keyword argument 'changedAt'`. I am sure that this is an error with the API as it used to work but I uninstalled and re installed and it is now broken. I have tried running just the below code and it doesn't work.
```
import mojang
`mojang.connect("EMAIL", "PASSWORD")
```
I am on windows with python 3.9.6 and pip 21.1.3.

Screenshot of bug (with personal info removed):
![pymojang_bug](https://user-images.githubusercontent.com/74084650/141428399-e0dce970-9777-4f6d-af37-254a44629caa.png)

**Comment by Lucino772** [comment]
It was a problem with the data received by the API, for some reason when using a **Microsoft** account I don't receive the same payload as **Mojang** account. For now, the data returned by the API is ignored, I'll later adjust the code so that the field `changedAt` is available.

**Comment by Lucino772** [comment]
This should now be fixed in release [v1.3.2](https://github.com/Lucino772/pymojang/releases/tag/v1.3.2)
